---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./objectbucketclaim.yaml
  # - ./scheduledbackup.yaml  # re-enable once the Barman Cloud plugin is installed
  # - ./prometheusrule.yaml
  - ./service.yaml