apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:A/gbADuGT0pIUOhds5QsoUjetLi2HLbVM0gK5GQkq2Tb375iGwrYlcQidp/HUoUg1BQV/u5PfqPvT+lgw8t5NtFt7ywsIHkeZg+OkJQ08etc5ojjcPNpeaFxiRfzhpnfoOpHAXZ0hkKQ4fBypPl1aM4uQoG6KUPi9YeiSve7YWwUl6tbqAHGHiXV4usuJHz5/LsW/F4AVpa76xHEpEOxoBkt4YQ5MvfQPnIzui/ZO7Bq+CNM1bzBeXwLlpVjxeYbAaI0TIeCM6rgGRP3pJa06wM8ELfbF6l5yuBSO8P3+CGPR+rBpgJh1NBrnqbFvC9Q,iv:c+9gPQjtFbkDGHWhuGe/6iPRNK1VC8xHvp/qQMHPPcM=,tag:ITbqGPVh02sQ2+I1gQ2Ztw==,type:str]
kind: Secret
metadata:
  name: ghcr-pull
  namespace: default
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - recipient: age10n5er0p64d5w7vqtj2shx82muqlcc7zmdx2yl70zn3l4ts8ah9zqf2s4ld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Wk14RmdUQjlGLzNWUkZa
        VlpLc0lGWUNEZ1ZodUM0bTJ0eGNKVXNYaGxvCmhIVVdzQ25pUE1kRXpYZkVBSm1n
        R0Y0TWh2TVJ0VmJ0MlUveUJWTGlUQjQKLS0tIDgvL2RiTXI5ZVdRZUNTOEMwZGt2
        M09wOEpiNWtoRGhhaG9CRENmUCswTE0K7MhYamE2pttTXfWjN/acAe2JULde/lVH
        57W01nfv9da+SCSvLaDDbN4JmtYOPDx7NTLbCSU1bg8xmpCNWwRriA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-28T08:04:54Z"
  mac: ENC[AES256_GCM,data:kSN6iAUnynfPRt9d/bwSxS02oLrYmZNGqtR580K3WN5dMATWEMWyIXP800qhKbQOkTVvz+om4A8EmrOmDCzM0YXFFQ9Okd9SmFmPHlbWNbmh7uKMG3UvfYi0+IPtj2xW8AYKXJcjzakSU1kl9mTE1BA3i7E+qZTkUKZFu/T7//8=,iv:+lMgIgYL1vgn1JQXaoYsfKRYvePub08jEpRR+YgYCns=,tag:FNdBiGmzz81UUc3h7++M2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
