apiVersion: v1
data:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:+hnAbqLovx+ReBCa,iv:Th/bQV1V59ActHQF/h7E++CGi5VCP9xSpbv+qLJOMNw=,tag:2EO4cSJp1jELJu1wncr2Gw==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:aAZN61HK569IfyeSuORZ2MUOSSrcf+uvFiolB39h/IpAJGZ2bYJBCA1JWVXthmx84kAhFw==,iv:7mJM59KtxTV+2h4BIhKzC3hGFJwi+aIy5qw240LBq+0=,tag:oTgTNXBFHmkx6OwZp7Ei9Q==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:JmPPBYiAGfXzMu9qmjeEFG05t3V6GVFxkgp+5fRVd9a7JGuXA3uuswBx+c8/xPaHR6Ya1PWUTBAHCcffurfOJg==,iv:/FTGgD05le2XK3p0iPrTCr4NPUO9ACo1aFbQwd2vKHQ=,tag:rbYvkohkczbtLHer5hHW8Q==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:yEJqBmwnePjzyqIt,iv:RMXzqgNAoyRu0YG3q1LCMM/Bcy0YudFPdXIuIneZJ28=,tag:j1FxA1Vqy4QXKrZjV5ylaA==,type:str]
  NEXT_PRIVATE_DATABASE_URL: ENC[AES256_GCM,data:N5RgLNwO2xDomORmNhk5VLkjvbi+0T0TGNwBWRdZ+QtfBEMrvM1IzHRMO3+q9HINM/t5GLHEVxO8rQeVKq+G7pPoIfS7FBlVYNwUwq9RPOlcdzScSKJqybO5kyDfCUhitcXMigmF+PCS4QtavsDZZKrVus8x6iNfCfSRYCzvV92fyfXLB4/Jqhbt9RWZxO/jJuVT7ueL1q/NEApydfSIguVTHhz3T16a,iv:enLXmrgXsTRYmq+pEV1s5yniEUkr/OEfy1hM+WRMOPE=,tag:2ptcTOs89QZj8Ox1u+IpQA==,type:str]
  NEXT_PRIVATE_DIRECT_DATABASE_URL: ENC[AES256_GCM,data:sUHFZF5OnkpplftDPQkKbcmCoGYc82w38Xpcvjg+MWKYkhX2S5bY/gX5zGquyDxQIjnONgYwWEVQ5lNCWAd7RMzWi6AyFquS10aMlFCyNgSKh+afFxyT9t9KjCkOkjWskE5FuTLz5LVMLk7ivcuPnJ5COkApukqk1RkMU/dDdhYFRVtrI04BrE/Pj/zSbfwNkw63iWYSCr50/4j2ShDMFpm0WJ4Rn7pb,iv:kjVUnFZjx8Wrh8GiB0x31HP4ra2vXWRBXFOjwQTv2NA=,tag:TR4kCndaicRaobiQtvclHA==,type:str]
  NEXT_PRIVATE_ENCRYPTION_KEY: ENC[AES256_GCM,data:XP08TJgdR3nzd0WTI7V6qas+k5LpcB2i9j4N5Fd86tiesNh4V2tme2yRi9wryP/xuPrbr0sKMcF5mYcRammHdgBxIMwWMiGMk1CFBRFV5XYbV6hKuLhT1A==,iv:2hnhHOzG9KaPKtzEOt+Kj2cwEKpTJIIhrITr2z521/4=,tag:woKbHu4BVPPZe7haKHVO+Q==,type:str]
  NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY: ENC[AES256_GCM,data:etP0aloZvOApITAc5anCkzV1CwW8c80o2Vh7TZrhtYBbNo0I2DUbKzdCt9ZBP6ZVN4nayv6RVmVTX/n108koousr0ebSsh4Msi9vZsini9G8fMRbZMApig==,iv:8fPRlD8cuHSzOJsnfzH/TBseoK91tvWhVdGyw1J7/60=,tag:c6lhP57FVQSfyNHkex1/Hw==,type:str]
  NEXT_PRIVATE_SIGNING_PASSPHRASE: ENC[AES256_GCM,data:NUlewHLLreXl49m/XP1034ft5CGife61ZTx4LQl7PT9eGuhV6WuL4JCVWug=,iv:Io/najoZa5P5WcfVrWSiEycyJpqEZfAs5zXIM/O2DdM=,tag:ZQq4zq6syfNy9SVsSunXWA==,type:str]
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:/8/dL34Tnq1yZSIrMntPlk6U8jrVYjoHgAtinyWCoW6MAzFdpqtUmhjZb5K+fXPgm4Tn1CGzSvbyqSZ+NNhOfnJ2OQk7qUzhXcNVKx5vppysvgcUFgQ15Q==,iv:JkZjmKNWYjXt01ltxBU2sslu7ZCiN4bhVnLgdrmUa/A=,tag:3QP/VYFrZLjzRh5G4ebXIQ==,type:str]
kind: Secret
metadata:
  name: documenso-app-secret
sops:
  age:
    - recipient: age10n5er0p64d5w7vqtj2shx82muqlcc7zmdx2yl70zn3l4ts8ah9zqf2s4ld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa3RkRUl6aW55bUFhNEZS
        NU5ybHpoQXFjVnBLOEFIZ1ZNNjh3V2p3UTFRCktqWkgvUE1nNDhHeXFxMW9MQ0w2
        YURNNzZLSUNzOVI3dXc4VU0vUUlmZTgKLS0tIFJPeExuWDNOd0J2alhDbEFYcVpJ
        dUZqekNibGlmQ3VxVG1nK0I2aGcvL1UK++3bPesyKse6fbRaoS9o09eJWRVlogpf
        SvTxmclb1+YEaL4tig4/99pJUUi2poYfy1QNpignDZMKnVORweu6YA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-26T19:23:53Z"
  mac: ENC[AES256_GCM,data:IZ4F0dV6uS1fsapQg/o+7ef9n6RxQRstdtkr7+5nhskZFxAVazZyVDitiqQolyKfQ+N4mSnaYl6E5F0NyUkYVcTXOiNjuxJOuYLXlMVzvu50RxbzDnCLT6Q6IF6gMzWr4XVkBMm4FIXnLz+JoA1SVH1JFtJxb6rNgvHQS1fgoWU=,iv:qzkAjP64OGLtByeDXKxPIDAEra2YvNB7X4G67+dVsb0=,tag:3I1gkCCa3fJyK3bqlnl41g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
