apiVersion: v1
kind: Secret
metadata:
  name: n8n-atrelix-app-secret
# N8N_ENCRYPTION_KEY: generated once at deploy; NEVER rotate (stored credentials
# become undecryptable). App DB role/database are created by postgres-init from
# the INIT_POSTGRES_* values below.
data:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:kiXN/rqWPrpwHgAnufRwFXsccPoBKATsAH7J7Z87PZU7j/Xhw4jmr+9YOmWSLZanUAMx3XX5E5JqEh9HEbmLrxqvG7z2GuKrm6mHX8BFdmJWawBvvsPIyQ==,iv:yIibpGsjloFP84ZlcaDKwBM21yCvr1QEypa+FOw1sFE=,tag:vK2eXuCjdQglPVuW/FCHqA==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:pK1il34IPFc3czGNKDB1dw==,iv:nZ7znaoiem2VQohc/qUNUoYco7NbgSuhaHhEANCGXKc=,tag:DW11mwlYTSAamVEJy0fNEQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:1VJ8TUvlxLvkLEco/R9BNscQ0JlWFw/Bxx9TDulz+ZQwLy2l74QrIMpJcCMnh1Qc6sub6wT8Y1CIQAh5p7jkjA==,iv:C5MuUdhScEveso83vw8x7Qs/NIGj9NkaVBXIGqzLpb4=,tag:kGwcnlYHaP+5VVyTEadUbQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:e3yO/4xitsw8oVnbG/CxgA==,iv:+adRYyelczxluwPNnKQ/a8vORlp6FABTECH7C29QOys=,tag:UvHM+VOQmAPe9xdqITmHow==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:GiTAWWcKwQ2063q8NOgIFuCtZj+r7LFs4ioXQq5iDvBKyHXNC5eidh1ffeGZz3VXzG1DiQ==,iv:WZC64bib0RmHZkCWg31RG3ZsTLJxgm/XIMfeDJCCTpY=,tag:AhE+DnpMdqVfxreoJeVBFA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:58OD6Hj9nzazeeHLaDQF2w==,iv:RI3vuyVLemK7bxGgJvXOuz41yGNi+pWktUhkIQ8dlHQ=,tag:h3SZONEXwb4Z1eR7kWX2Pw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:yWkfxIpEqy2GciZUlmIa8Vto+WY7kXsjWGnigu4UOD1NeKuU+IcZUkWgTtE/bpSgzgLck/m2GZr6aV552/5ftQ==,iv:1PnyghKlfZv+kBQa3V9mLML9aI5lhY2mhZNAiBod9R4=,tag:+nL6aHD7OTJAfSZFwzvo9g==,type:str]
sops:
  age:
    - recipient: age10n5er0p64d5w7vqtj2shx82muqlcc7zmdx2yl70zn3l4ts8ah9zqf2s4ld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuM2VrcXYxUmN6ZXg1em1v
        WmhxQ2ExcXFyZkIvTWRYbldhck1iOUN1TGwwCjRWUDRPSXQreHYwVkQ3U1pjK01o
        ZW9LbzFDWGVXT2JhMThrT3I2R0F2azAKLS0tIDVMeVlaQ1lJcmJRZ2xvVUc2MFZY
        Y1ppVVFKMnh2TWM0dUlyOUFFR2J5dFUKSCyDVbIJ2lhPp+0ReVe/N/r/4BnIs+sV
        rqSI8vWjyOjLEOAOXowbKqjqwchfFU1CcKabIQpDnRh5lcDaxMxJ8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-28T08:38:21Z"
  mac: ENC[AES256_GCM,data:McldtYcMeKKHCZmpKc/cbFeqMvvVfH61PlVUGcQsEfsjNkJ9VLHQpdG2/O9FJ82s0Ue3BdM1LqtY+8ANAnZKuHore5lA8DdMGx5GCE/kgNv7EgJuN/zzusv+/jHnwvSaK5bjWKZcgyc05qvXPILEYlbKkWQ3DFPPojSQUIC74HM=,iv:bdPkkXe8zutIkh5D/8hTYlTbWnzvyseni5rPuFM00V8=,tag:dgCr4IUJ+178LuS0ndHBeQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
