apiVersion: v1
kind: Secret
metadata:
  name: dario-secret
  namespace: default
type: Opaque
stringData:
  #ENC[AES256_GCM,data:km1ismExgjPxnNee9Zvxqp//oNn+DtUcPTDDyaVQrcQd7ynsrZt88bhibyHY7Ungc6MkCtyT2NFHTIvqR5LGbeWcAbApXv0ziStl+g==,iv:oXzMUzAEJXaGcsy1YhYzRWCLPtH7qZtlFmL+EgPQydg=,tag:uCY4Gb11MNx92DGmaJEvew==,type:comment]
  #ENC[AES256_GCM,data:p4picVgkbg9IOY7oUCVJ09z4i5c5br5HJbmxyW9pGJI/JSpMRtuOnfUj7iRX/nSYHM55DSG1pFP50/UX1+n/Rfe0eVAzXnbgrUt5Hoi4H8o=,iv:mecl/9Z4PECnsO4JSt11NxsJ6wSMzs8uQZcJUeGm2fQ=,tag:WBz+/gIraUkjtjTccwBwlQ==,type:comment]
  DARIO_API_KEY: ENC[AES256_GCM,data:AAYlbT9vvJTex8daSxAudHIXdbq+HsN+HF5/kmWhqjqSnQeIAO+C2qvUeQY71kcSHxSZqQ4UOfw/niyFBZp+Mw==,iv:aQtE7IC9smgqPOCDqUg4ycgrdOvC71HB8zS2noh1cW4=,tag:Q2L8Lg1l0nOPcJE1hXh6YQ==,type:str]
  #ENC[AES256_GCM,data:tl+jcKUgVCg2ERCzLRZL0nxaUaxLyhDh3Rjicyuw1c34rulyA6D6i2IsPYyODEG+MQes9VJpvh9c1Q==,iv:aca/EEDL2vX+3wQiT84/2dO9o+ZHswJN1x4+7zoCu9g=,tag:HyhVJBjBY/DRyjjsReY3cw==,type:comment]
  DARIO_ADMIN_TOKEN: ENC[AES256_GCM,data:CaxOvuSYgutjf5NX5UhLPPRWrV3LdNAU7J8LM0w/VEgx6NTX5UmUCS8QDu0kWmDS21FEXddXqzvx5DeKn2ceDw==,iv:2VrmEtmOqwripOuareH5q2RclALikKiKKANo1hD4CuY=,tag:VQfXKR7danMsWcspLVspBw==,type:str]
sops:
  age:
    - recipient: age10n5er0p64d5w7vqtj2shx82muqlcc7zmdx2yl70zn3l4ts8ah9zqf2s4ld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWXdjdS9Cb3IrYVYrRjdr
        bTdSOVgraGgzTTJ5bG5EbFNsNHluUytBejNNCnBWRFh3dEVrUUNhSm12RHUzNFFk
        Sm1neFBLdkJkV25HQnBYSkQwcmZaM2sKLS0tIFlURHZTaG9tUU9WcDhZNjFOSmI1
        ZFJ6a3p0ZFNWcTY0NU5ObmpwWTR3VncKzjL7whEmmdoQVQojAGJ+FukvTNwlZLEM
        FRK5h4GWdCrQbr7unHzOKRoo0js8M63hGCu1IqPE6K4Rz7ds4bpdRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-01T23:24:44Z"
  mac: ENC[AES256_GCM,data:89dbviYXIxjtg+2Kgp+ClU8MabUTFxlxe/glDkuLqMScuJFI4HMZm7jujx/0QlrB/sriXQVxe2g5G18Iu8lqTMb7cybjnMPyshSqc2EhzIPRAj4JamyRYZZVNBvm3ZEXSuiwZhik9dGhasyUm5NIog53ycl/U1X+qYXe2wrf1sk=,iv:N1NOJ7y+nZXy1ajsmZ8ZfT9YKdS2AHSmt6gJCqvgJAI=,tag:HwpZ9RJzHGtAr8hULMvgbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
