apiVersion: v1
kind: Secret
metadata:
  name: hudu-app-secret
type: Opaque
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:zGiH6ua8bWIjWceoH+N2kWgSXvMzt9qX1sT18Qs10CPk87p7z4xG65mW8dbnuieADD4Kys5dk3+fNHnJ7JOAKZM30Uu+GIOqfXmWDmEM3zhzKHMBScL85Z3G/bzoxwffIHUY+u1t6YYdhftFwgULJPvb+nFN/fDSInEq3c9jJwQ=,iv:Mc8sxNgesXXR7b4tgz+LbdEbchJnMrMEIDuwSNy6lwo=,tag:gAU+QiCQ8tCZ1sswyn2btg==,type:str]
  PASSWORD_KEY: ENC[AES256_GCM,data:lboI50EjjoX4kAoU8jENptl7bgFiATK5+T68ZnixX2s=,iv:0TzDWgsEOwYP7SRhdJKWeevXjhuVXmz1szJ6/RTsI74=,tag:ZRWpjXWIRIiVc2czZU6f8Q==,type:str]
  TWO_FACTOR_KEY: ENC[AES256_GCM,data:6ZGZrRTadeGr+9apAPVUGHIYVmgMZFvJe37h6lOQy0I=,iv:I0OlOOzzIjPLueObyrL3mTseCqN7G5GUxClqezyqHhM=,tag:95uqpokOifXpVFgRVMU5+Q==,type:str]
  DISCOVERY_CLIENT_SECRET: ""
  SMTP_USERNAME: ENC[AES256_GCM,data:+r2rskAw,iv:POGO9g3WNYkM6eXVvFW61mpPytmi1GeO5vN80tfm3jc=,tag:bQni3JlhN1RsPiYQk6XErQ==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:y04ni2LO28O/gIJAv4dJQ4h+O2eYwVtllxZIDTF/qABAcWPwEBl3ClbFUHSdDsv7uosA3CIda3QLN7kdzprIFWt8HERl,iv:C1IIbeU8xAoJujmBNhRQeYeDLNxDZaW8qab9DVIWmTw=,tag:3+iJL/npYM0hZ6wwkODZ+w==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:6/5wPskcFBAmebwaXTnQFMV5mnxKZtHKbVC/FKEi+eGAnELU9DkfeZufN9AHp+xYhA==,iv:V5FtAOHXnXEUz8WH4u524PLXnZC8JH0ZTcctjdk/0to=,tag:XtBQzK1zWBo7pRkRWcFphw==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:/+7YHbr3kzKuZHd6dL7zDX4Qatb5,iv:4o8A1HEf8S+fR7X9BcW0nv1C3DNPkWCIwm67b6xXI74=,tag:jA+8/zN6umaiGAax0YGLLg==,type:str]
  S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:RzzR2HFcb7QangoYkj7SX+WWn1yy,iv:O9+ZjB9ANi/8HaOu0Py4AdfWyNF733MELsbMy1OWbT4=,tag:YrLK/FpfP3o8/7faHPF06w==,type:str]
  S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GwS1fVjmZ2hPJuFjL74GkKslxtZM4bxOvMqsHo1vGyyK6FLer94HCgu0AIkcy+Ninr8u3+LYyPcm6WJJN+cy8w==,iv:S8NOABB7Yeypzg0ZR7sWob0VnvsdSiVyDkW4JGJQdt8=,tag:gHURo5FbCvz5vFuhVsIYcA==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:QmNc5jkeHKcdZf1PYdIjLtoGr22iGcupS5rgD8XIAZordN1eobs=,iv:sRA/MjNKcSQ2xa83/Bv7+yc9mTSup8ZdSMJkrQ9Cuqc=,tag:+SAhEvvYjn4QViKcQ8zDJw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:BOaqbfo6C/EC4VS6pGhD,iv:ufCLonemstejTYEF+x3+8hMFBltL4yI3Wb54sUpZ4eg=,tag:6ZQDUOCXXVp19kQApobq2w==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:McZDFA==,iv:33ZEq7mYNaP6Q19Mu60GFFuHfwsPyYSsKI4lsF8ujow=,tag:sE0M0pg5o7wrpPgaChNCqw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:EI/CVJsaDAr0W6Tex3/wdQI+mCvdlcYvy2ARmyFYDseuEf6amJoBO792lUXo8L7l,iv:8QCyNQtSP/4P9433Il92WukGOHE6pMOoVECEMVhRy64=,tag:9s7UaIyqy9aPqareZeo5Pw==,type:str]
sops:
  age:
    - recipient: age10n5er0p64d5w7vqtj2shx82muqlcc7zmdx2yl70zn3l4ts8ah9zqf2s4ld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b004L25hbXZycEhuSHBE
        dXpONTZlTXQyZmtTVWpiRmZGZzN6ZlY3MGpRClZ5d3NQUzRpeUFxWXYrRFJGbFpx
        elgxQzZGa2FDL0NSSjh6MnJweXY0czgKLS0tIFlWYXVlN3RyajFMbE1LN0RYaGRD
        N29TdlJHNTg1UVQwWW5WMnVJenV4eWcKCC9CoXSFIjsjzPFhKWeYRTW1yD90WTH8
        aZ7ZC+thiuEpRjoo3XVqqKNLdKfnE/BS3bI3kd1y0SttkouxEIkzWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-08T17:52:22Z"
  mac: ENC[AES256_GCM,data:zqZLQjw+w76TPt8T2eYhaopdNpMl24n+62kO6t2NVoy+IAAU+x0i1ZX63Ig1I8Jw74DXYvPQtgmYpv9kX1CkY3I1qQhenIPnV6cA8b9Bworo2sLsjS4yqkgkaXgb5Xd+0u5vRglhzA3EB4uPNaJKDj7KnbXRbIv6ul7J5SbbaZ4=,iv:6KukZj5yv/qlJV7SwlBpyVDsb3SYLgRNXwhA7SRE9is=,tag:tNcdhhdaX8SBH8C83orVKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
