apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:w3kvR4Q4PN0g5v4=,iv:zwGn4aDmOaTHpNCKkVwkNlskCmU2fk0OXEBZK583wio=,tag:7KF1WzIni5s+GJIAz+3bdw==,type:str]
  ONEPASSWORD_CONNECT_HOST: ENC[AES256_GCM,data:TOEbQX7zP1QpQ5sFqZgGERMg7SFoe1g=,iv:Rjakqw6XAmySpc+x6FjFj4p9FQkoxv8g7+bMKX9jOFw=,tag:/Qzeu4dAHl/oY5700xvrcA==,type:str]
  SECRET_NFS_IP: ENC[AES256_GCM,data:7ojCwixdGIk4XDU=,iv:kBoUP2CdX5EdeH92AYm4EibbyW5qh+zBZ/eCv1BMRMQ=,tag:0pzGTIL50h0kMbC/xJnYdg==,type:str]
  SECRET_NFS_DOMAIN: ENC[AES256_GCM,data:gnt2CZTS,iv:XWtUzfS4FCS0VuyU6GJ7OmmMdCQ+hrUOPP8ev9o83Uc=,tag:qWOnu/Vo6W4kNBsvrRcrUA==,type:str]
  POSTGRES_IPV4: ENC[AES256_GCM,data:c2aX7lgzW9wt+18=,iv:JJBMQcsVq/97bSd4KsdXCnGjNlo3ES5o5ToyvE1GgSE=,tag:51P20g0HEBvvYyN77/LwFA==,type:str]
sops:
  age:
    - recipient: age10n5er0p64d5w7vqtj2shx82muqlcc7zmdx2yl70zn3l4ts8ah9zqf2s4ld
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMXI3Ums3a1FsZmtyaFQz
        UWU2Y2FWckRkSGRGWmlVd2dTbmh2RUUxc1RJCldKYXZpc1hzQWtoS2k5L3VxVG1v
        bDRqajVZUFgzclp6SndBcG9sRkJvYVEKLS0tIGZoU2xsN0JEbUtjRnBNRGo4VlNn
        bzRXZ3luTTJ0SzhPTUh0RGxZUUJiT00KaNScPJ64UzynCbSeJYczE3r6Vx+rcZka
        j7loGqwptpgLNgGvUkSfXqgQcZ5hJSvscoro9qZ0zZ6OYd+z1DjWDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-31T06:26:28Z"
  mac: ENC[AES256_GCM,data:8XZDX7eBrK/xTw+f4/ZCoyp+xdWMB5vklPaW/enz8wEG7t85ZVUnmBMys/5HwkrthzUiXOHvHqJVtGF+XDfOgLKujzJrBDN8FR6lddyy6/X8/oK7eNZdD8xQdwPUV5pLGYjOtzntcYHRXjx7gGAMrmLe+db3lvtT+qpfRCPAcOQ=,iv:EukL5J5jMyRLZyK+ZNkwjS3Uq5Srqm5vxRJPNDMQn3U=,tag:LBTrymFs+XJRhuLlsmQ/kg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
