apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
stringData:
  client_id: ENC[AES256_GCM,data:NiUfJjy5CqiheVMFYtNYfp4=,iv:KFSkyhD1s7YIFHM/E6EN4HbUL3tazwu8T3BRZA+NeHk=,tag:vWvwsQjuwBOQ8IDUxVBfRQ==,type:str]
  client_secret: ENC[AES256_GCM,data:Pet4eYdoMJb+rZfC6u7k22Rt5YyJBXHj9mKfTdU1XGeWrK6dwVyr84o1uE10gL6nvdNOtCQXG2v49LMhkuozlA==,iv:sijGyag/TGoQxtQUzoIr2rs8AcYYrStFvfp9lBFwTw0=,tag:B7cY3tIoA4Vg3Lfx95e7Qw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUjdVVWZJcExhcWhlOVpk
        Mk5OWEZRL2xSN3VramZGK2xpQVB3Si9CRVhNCitkTitVQm1qV1BtSGlsd2lZN3E3
        Ym0weFBjbHJacVVTUU95MWF3Zm15TkUKLS0tIFVUTzEzeTB0OTFUTWpOQTFia2Fh
        THQzNWUyQk56elc2elFqRGF1SytzdFEKN2hn/iws44MT81ZUhAlcZXS0YRtMhXs6
        9RSgGWg4VnQ/Ho3CZ13EGYzk1iQs0p0L9s4eDrS77ClewIhZXqdqOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age10n5er0p64d5w7vqtj2shx82muqlcc7zmdx2yl70zn3l4ts8ah9zqf2s4ld
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-28T09:29:19Z"
  mac: ENC[AES256_GCM,data:/qpZmjW4zdnF6rtltJfoZlhL7qqsww1UzjEXD3/YlK4r0y1503Y6jN9OplFe2D59fSEvG5EXFnysmDc9JusUeFsHqKb5HAvJ4aqrbLXC7hhZWzx7zPhNby+XvSy7IeDT/Gp5S2Ws6RmM1L1jx/7CL3sAn/lslTHflErb2mLbMoc=,iv:nwydGR10gNkjaXyjQoRv36sL2UimbGRb0hBOXc9rp6E=,tag:4x9S+Vf+xU6yZxnUrNyu3A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
