---
instance:
  distribution:
    # renovate: datasource=github-releases depName=controlplaneio-fluxcd/distribution
    artifact: v2.9.5
    version: 2.x
  cluster:
    networkPolicy: false
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    url: "https://github.com/tturnerdev/home-ops.git"
    ref: "refs/heads/main"
    path: kubernetes/flux/cluster
