---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
spec:
  interval: 2m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: internal-ingress-nginx
      namespace: network
  values:
    controllers:
      ntfy:
        containers:
          app:
            image:
              repository: docker.io/binwiederhier/ntfy
              tag: v2.28.0@sha256:6ef4b819f722fccdc036af611c4774cfdc2de821ab74fdd48bbf4c9d6f8973da
              pullPolicy: IfNotPresent
            args:
              - serve
    service:
      # Configure a service for the main application
      app:
        controller: ntfy
        type: ClusterIP
        ports:
          http:
            port: 80
    ingress:
      # Configure an Ingress for the main application
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host